name: PR Title Validation

on:
    push:
        branches:
            - "**"
    pull_request:
        types:
            - opened
            - edited
            - review_requested
            - synchronize
            - reopened
        branches:
            - "**"

jobs:
    should-not-change-jir-no:
        runs-on: ubuntu-latest
        steps:
            - name: setup python
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - name: print env
              run: |
                echo $GITHUB_EVENT_PATH
                cat "$GITHUB_EVENT_PATH"
                current_title=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH")
                old_title=$(jq --raw-output .changes.title.from "$GITHUB_EVENT_PATH")
